//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/plondhe/Repos/Srujan/Srujan.Test/सृजन.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IसृजनListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class सृजनBaseListener : IसृजनListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="सृजनParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] सृजनParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="सृजनParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] सृजनParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="सृजनParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] सृजनParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="सृजनParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] सृजनParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="सृजनParser.breakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakStatement([NotNull] सृजनParser.BreakStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="सृजनParser.breakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakStatement([NotNull] सृजनParser.BreakStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="सृजनParser.arrayDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayDeclaration([NotNull] सृजनParser.ArrayDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="सृजनParser.arrayDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayDeclaration([NotNull] सृजनParser.ArrayDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="सृजनParser.arrayAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayAssignment([NotNull] सृजनParser.ArrayAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="सृजनParser.arrayAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayAssignment([NotNull] सृजनParser.ArrayAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="सृजनParser.arrayAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayAccess([NotNull] सृजनParser.ArrayAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="सृजनParser.arrayAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayAccess([NotNull] सृजनParser.ArrayAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="सृजनParser.arrayInitialization"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayInitialization([NotNull] सृजनParser.ArrayInitializationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="सृजनParser.arrayInitialization"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayInitialization([NotNull] सृजनParser.ArrayInitializationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="सृजनParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclaration([NotNull] सृजनParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="सृजनParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclaration([NotNull] सृजनParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="सृजनParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] सृजनParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="सृजनParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] सृजनParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="सृजनParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] सृजनParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="सृजनParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] सृजनParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="सृजनParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseStatement([NotNull] सृजनParser.ElseStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="सृजनParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseStatement([NotNull] सृजनParser.ElseStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="सृजनParser.whileLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileLoop([NotNull] सृजनParser.WhileLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="सृजनParser.whileLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileLoop([NotNull] सृजनParser.WhileLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="सृजनParser.printStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintStatement([NotNull] सृजनParser.PrintStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="सृजनParser.printStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintStatement([NotNull] सृजनParser.PrintStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="सृजनParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] सृजनParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="सृजनParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] सृजनParser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="सृजनParser.comparisionOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparisionOperator([NotNull] सृजनParser.ComparisionOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="सृजनParser.comparisionOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparisionOperator([NotNull] सृजनParser.ComparisionOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="सृजनParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] सृजनParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="सृजनParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] सृजनParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="सृजनParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] सृजनParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="सृजनParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] सृजनParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="सृजनParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] सृजनParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="सृजनParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] सृजनParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="सृजनParser.functionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionName([NotNull] सृजनParser.FunctionNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="सृजनParser.functionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionName([NotNull] सृजनParser.FunctionNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="सृजनParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] सृजनParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="सृजनParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] सृजनParser.FactorContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
