//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:/Repos/Srujan/Srujan.Lexer/ANTLR/सृजन.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="सृजनParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IसृजनVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] सृजनParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] सृजनParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.inputStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInputStatement([NotNull] सृजनParser.InputStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStatement([NotNull] सृजनParser.BreakStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinueStatement([NotNull] सृजनParser.ContinueStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] सृजनParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.arrayDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayDeclaration([NotNull] सृजनParser.ArrayDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.arrayAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAssignment([NotNull] सृजनParser.ArrayAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.arrayAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAccess([NotNull] सृजनParser.ArrayAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.arrayInitialization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayInitialization([NotNull] सृजनParser.ArrayInitializationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaration([NotNull] सृजनParser.VariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] सृजनParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] सृजनParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseStatement([NotNull] सृजनParser.ElseStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileLoop([NotNull] सृजनParser.WhileLoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.printStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintStatement([NotNull] सृजनParser.PrintStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] सृजनParser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.comparisionOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparisionOperator([NotNull] सृजनParser.ComparisionOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.logicalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOperator([NotNull] सृजनParser.LogicalOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.bitwiseOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseOperator([NotNull] सृजनParser.BitwiseOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.complementOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplementOperator([NotNull] सृजनParser.ComplementOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] सृजनParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] सृजनParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] सृजनParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] सृजनParser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.functionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionName([NotNull] सृजनParser.FunctionNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="सृजनParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] सृजनParser.FactorContext context);
}
